name: Run SoapUI Tests

on:
  workflow_dispatch:

jobs:
  soapui-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download SoapUI 5.9.1
        run: |
          wget https://github.com/SmartBear/soapui/releases/download/5.9.1/SoapUI-5.9.1-linux-bin.tar.gz
          tar -xzf SoapUI-5.9.1-linux-bin.tar.gz

      - name: Run SoapUI Tests
        run: |
          ./SoapUI-5.9.1/bin/testrunner.sh -r -j -f soapui-reports MyProject.xml

      - name: Upload JUnit Reports
        uses: actions/upload-artifact@v4
        with:
          name: soapui-junit-reports
          path: soapui-reports/*.xml
